version: 2
root-markers:
  - .git/
lint-debounce: 1s
log-file: /tmp/efm-langserver.log
log-level: 1

tools:
  prettier: &prettier
    format-command: 'npx --no-install prettier --stdin-filepath ${INPUT}'
    format-stdin: true

languages:
  typescript:
    - <<: *prettier
  typescriptreact:
    - <<: *prettier

